frontend:
  port: 3000
  label: todo-frontend
  replicaCount: 1
  image:
    name: eneskzlcn/todo-frontend
    tag: latest
  servicePort: 8090

apiVersion:
  secretsConfigs: v1
  deployments: apps/v1

deployEnv: test