

db:
  user: cG9zdGdyZXM=
  password: dG9kbzEyMw==
  dbName: cG9zdGdyZXM=
  servicePort: 8050
  containerPort: 5432
  label: postgres
  image:
    name: postgres
    tag: latest
  pv:
    capacity: 100M

api:
  port: 4000
  label: todo-backend
  replicaCount: 1
  image:
    name: eneskzlcn/todo-backend
    tag: latest
  servicePort: 8080

apiVersion:
  secretsConfigs: v1
  deployments: apps/v1

deployEnv: test