apiVersion: {{.Values.apiVersion.secretsConfigs}}
kind: Secret
metadata:
  name: {{.Values.db.label}}-secret
type: Opaque
data:
  user: {{.Values.db.user}}
  password: {{.Values.db.password}}
  dbName: {{.Values.db.dbName}}
