apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{.Values.db.label}}
  name: {{.Values.db.label}}-pv-claim
spec:
  storageClassName: {{.Values.db.label}}-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.db.pv.capacity}}
