apiVersion: {{.Values.apiVersion.secretsConfigs}}
kind: Service
metadata:
  name: {{.Values.frontend.label}}-service
spec:
  type: LoadBalancer
  selector:
    app: {{.Values.frontend.label}}
  ports:
    - protocol: TCP
      port: {{.Values.frontend.servicePort}}
      targetPort: {{.Values.frontend.port | b64dec}}