apiVersion: {{.Values.apiVersion.deployments}}
kind: Deployment
metadata:
  name: {{.Values.frontend.label}}-deployment
  labels:
    app: {{.Values.frontend.label}}
spec:
  replicas: {{.Values.frontend.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.frontend.label}}
  template:
    metadata:
      labels:
        app: {{.Values.frontend.label}}
    spec:
      containers:
        - name: {{.Values.frontend.label}}
          image: {{.Values.frontend.image.name}}-{{.Values.deployEnv}}:{{.Values.frontend.image.tag}}
          ports:
            - containerPort: {{.Values.frontend.port }}
          env:
            - name: BACKEND_URL
              value: {{.Values.backendUrl | quote }}


